#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Aug 27 01:38:56 GMT+01:00 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
